rootProject.name = "workaholic"
include("kubernetes")
include("vcs-integration")
include("gateway")
include("exception-processing")
include("datasource:datasource-work")
include("datasource:datasource-pod")
include("datasource:datasource-transaction")
include("rabbitmq:mq-vcs")
include("rabbitmq:mq-kube")
include("rabbitmq:mq-error")
